title: "MagosIT Kft"
sub_title: "Egyedi és csúcsfejlesztés, tanácsadás, K+F"
show_date: false
settings:
  gm:
    quality: 80
  light_mode: false
  reverse: true
sections:
  - type: navmenu
    home_text: "Főoldal"
    contact_text: "Kapcsolat"
    goto_text: "Ugrás"
    facebook: "https://m.facebook.com/Magosit-Kft-108385110710092/"
    linkedin: "https://www.linkedin.com/company/magosit-kft/"
    twitter: "https://twitter.com/magosit3"
    github: "https://github.com/prenex"
    blog: "http://ballmerpeak.web.elte.hu/devblog/"
    email: "magosit@outlook.hu"
    phone: "+36 20 974 4324"
  - type: full-picture
    image: banner0.jpg
    text:
      title: MagosIT Kft
      sub_title: "Csúcsfejlesztés, üzleti szoftverfejlesztés, tanácsadás, K+F"
  - type: quote
    text: "Látni azt, amit mindenki lát és olyat gondolni, amit senki sem gondolt még."
  - type: header
    text: "Szolgáltatások"
    menuid: 'services'
  - type: subgal
  - type: header
    text: "Rólunk"
    menuid: "about"
  - type: paragraph
    css:  "text-align:center;color:grey;margin-bottom:4vh;"
    title: "Programozási nyelvek"
  - type: polaroid-group
    margin_bottom: 20vh
    images:
      - name: cpp.png
        x: 3vw
        y: 0vh
        w: 15vw
        h: 30vh
        angle: 15
        text: "Modern C++ és C"
      - name: java.png
        w: 30vw
        h: 60vh
        angle: -15
        text: "Enterprise Java (JPA, EJB3, JSF2, AspectJ, MQ)"
      - name: c_sharp.png
        x: 45vw
        y: 35vh
        w: 15vw
        h: 20vh
        angle: 20
        text: "C#, .Net"
      - name: python.png
        x: 45vw
        y: -6vh
        w: 25vw
        h: 35vh
        angle: -25
        text: "Python (flask, jinja2, REST, Blender scripts)"
      - name: html_css_js.png
        x: 5vw
        y: 35vh
        w: 23vw
        h: 25vh
        angle: -33
        text: "Web 5.0 (Html5, CSS3, JS)"
  - type: paragraph
    css:  "text-align:center;color:grey;margin-bottom:4vh;"
    title: "Modern Futtatókörnyezetek"
  - type: polaroid-group
    margin_bottom: 20vh
    images:
      - name: android.png
        x: 3vw
        y: 0vh
        w: 15vw
        h: 20vh
        angle: -15
        text: "Android"
      - name: linux.png
        w: 30vw
        h: 50vh
        angle: 15
        text: "Linux és nyílt forrású rendszerek"
      - name: oracleplsql.webp
        x: 45vw
        y: 3vh
        w: 15vw
        h: 23vh
        angle: 35
        text: "SQL, Oracle, PL/SQL"
      - name: godot.png
        x: 5vw
        y: 20vh
        w: 20vw
        h: 25vh
        angle: -35
        text: "Godot játékmotor"
      - name: unity.png
        x: 42vw
        y: 25vh
        w: 16vw
        h: 25vh
        angle: 5
        text: "Unity 3D játékmotor"
  - type: paragraph
    css:  "text-align:center;color:grey;margin-bottom:4vh;"
    title: "Fejlett technológiák"
  - type: polaroid-group
    margin_bottom: 20vh
    images:
      - name: AR.jpg
        x: 3vw
        y: 0vh
        w: 15vw
        h: 30vh
        angle: -15
        text: "ARToolkit5"
      - name: opengl.png
        w: 40vw
        h: 43vh
        angle: 10
        text: "OpenGL, OpenGL ES2, WebGL"
      - name: vuforia.png
        x: 45vw
        y: 22vh
        w: 17vw
        h: 21vh
        angle: 35
        text: "Vuforia"
      - name: directx.png
        x: 3vw
        y: 20vh
        w: 20vw
        h: 25vh
        angle: -35
        text: "Microsoft DirectX"
      - name: blender.png
        x: 15vw
        y: 25vh
        w: 15vw
        h: 30vh
        angle: -12
        text: "Blender 3D modellezés"
      - name: git.png
        x: 37vw
        y: 32vh
        w: 16vw
        h: 20vh
        angle: -5
        text: "Git (workflow, setup, hosting, advanced)"
  - type: paragraph
    css:  "text-align:center;color:grey;margin-bottom:4vh;"
    title: "Fejlett megoldások"
  - type: polaroid-group
    margin_bottom: 20vh
    images:
      - name: microservice.png
        x: 3vw
        y: 5vh
        w: 17vw
        h: 35vh
        angle: 15
        text: "Mikroszervíz, elosztott és párhuzamos programok"
      - name: optimization.jpg
        w: 35vw
        h: 45vh
        angle: -15
        text: "Kód optimizáció (Új algoritmusok, cache, assembly)"
      - name: OSGI.jpg
        x: 50vw
        y: 22vh
        w: 20vw
        h: 35vh
        angle: 35
        text: "Komponensalapú fejlesztés (OSGi, Equinox, Apache felix)"
      - name: jenkins.png
        x: 45vw
        y: -6vh
        w: 25vw
        h: 30vh
        angle: -25
        text: "Devops, CI (Jenkins, Chef, Shell)"
  - type: paragraph
    css:  "text-align:center;color:grey;margin-bottom:4vh;"
    title: "Alapítók"
  - type: paragraph
    text: "Vállalatunk jelenleg saját erőből, külső üzleti célú befektetők nélkül, három családon belüli tulajdonossal működik. <b>Thier Richárd István (80%)</b> minősített többségi tulajdonosként és a fejlesztések, innovácók vezetőjeként személyes részvétellel is bekapcsolódik a fejlesztésekbe. Szakterületileg szerteágazó, üzleti alkalmazás fejlesztésen át kutatás fejlesztés és innováció területekig minden szakmai tevékenységben is érintett, a vállalat stratégiájának és alapvető üzleti képének kidolgozója. A vállalat alapítását megelőző évkben technikai vezetőként, pályázatíróként és intrapreneur-ként is végzett munkákat. <b>Thier Roland Tamás (15%)</b> második legnagyobb résztulajdonosként és társalapítóként az igényes fiatalos lendület megtestesítője, mindig fordulhatunk hozzá ipari, megjelenésbeli, design és zenei tanácsokért. <b>Thierné Dr. Papdi Gyöngyvér Enikő (5%)</b> társalapító és résztulajdonos hivatásos Neurológus orvosként több konferencián korábban sikeresen szereplő személyként kiváló tréning, működési és oktatási tanácsokkal segíti a vállalat működését."
    image:
      name: owners_tech.png
      float: left

# vim: ts=8 et sw=2 sts=2
