title: Szervezeti
sub_title: Oktatás, transzformáció, képzés, tanácsadás
date: 2020-01-03
cover: organizational.png
#light_mode: true
sections:
  - type: full-picture
    image: organizational.png
    text:
      title: ...TODO:...
      sub_title: ...TODO...
  - type: quote
    text: "Nincs oly rakott szekér, melyre még egy villával ne férne."
#  - type: full-picture
#    image:
#      name: video.mp4
#      type: video
#    text:
#      title: Beautiful Title
#      sub_title: pouet pouet
#      date: 2015-12-08
#  - type: bordered-picture
#    image:
#      name: video.mp4
#      type: video
  - type: bordered-picture
    image: stuff.png
#  - type: bordered-picture
#    image:
#      name: video.mp4
#      type: video
    text: "plop"
  - type: bordered-picture
    image: stuff.png
    text: "plop"
  - type: text
    text: « voici plein de blabla à rajouter et <b>ceci est du gras</b> et encore plein plein plein plein de text car je veux voir comment ça va wrapper car c'est important et il faut pas que j'oublie de mettre des margins en % sinon ça va pas le faire alala là ça devrait aller »
  - type: pictures-group
    images:
      -
        - name: stuff.png
          text: "test"
#        - name: video.mp4
#          type: video
        - name: stuff.png
          text: "test"
      -
        - stuff.png
        - name: stuff.png
          text: "more stuff"
  - type: pictures-group
    images:
      -
        - name: stuff.png
          text: "test"
        - name: stuff.png
          text: "test"
        - name: stuff.png
          text: "test"
      -
        - stuff.png
        - stuff.png
  - type: full-picture
    image: stuff.png
#  - type: full-picture
#    image:
#      name: video.mp4
#      type: video
